### ISSUE TITLE
V3 Themes API Not Working

### ISSUE THREAD

**Issue by PeteyRev** [getconversio/node-bigcommerce#33] opened 2017-09-01 20:30 UTC
Hi, I am trying to get my stores current theme but this does not seem to be working:

[themes api](https://developer.bigcommerce.com/api/v3/themes.html#themes-api)

```
var BigCommerce = require('node-bigcommerce');

var bigCommerce = new BigCommerce({
  clientId: 'clientId',
  storeHash: 'hash',
  accessToken: 'token',
  responseType: 'json'
});

bigCommerce.get('/themes', function(err, data, response){
  console.log(data)
});
```

I am getting this error

`(node:64686) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Request returned error code: 404 and body: The route is not found, check the URL
`

**Comment by dlebech** [comment] 2017-09-04 10:36
@PeteyRev I added `apiVersion` as a config parameter and published this to NPM as version 2.5.0. Your example could then be updated like this:

```javascript
var BigCommerce = require('node-bigcommerce');

var bigCommerce = new BigCommerce({
  clientId: 'clientId',
  storeHash: 'hash',
  accessToken: 'token',
  responseType: 'json',
  apiVersion: 'v3' // This is new
});

bigCommerce.get('/themes', function(err, data, response){
  console.log(data)
});
```

**Note**: During testing, I noticed that BigCommerce has not transferred all existing endpoints to v3 so e.g. calling `/hooks` will not work here. You will have to work around that until v3 has feature parity with v2.

I hope this helps. I'll close this ticket for now.

**Comment by PeteyRev** [comment] 2017-09-04 16:10
Thanks for your help @dlebech, I was able to get my themes just fine. Just to clarify, are you saying that calling the hooks like `POST /themes/{theme_id}/actions/download` will not work until the existing endpoints are paired with V3? My end goal is to pull the current theme to my local machine stencil CLI env via npm script. Currently stencil only offers a `stencil push` command to bundle and upload a theme, but nothing for pulling.

**Comment by dlebech** [comment] 2017-09-04 17:13
@PeteyRev I don't know exactly what endpoints are not replicated yet, but for example, if you try to fetch `/hooks` on v2, it will work, but it will not work on v3. Honestly, it might just be that I'm missing something here of course. Perhaps `/hooks` is actually deprecated and replaced with those endpoints you mention. I haven't been following the progress of v3, so just ignore me if everything is working for you as you expect :smile:

**Comment by PeteyRev** [comment] 2017-09-05 22:50
@dlebech Well it seems like it _should_ be working - I think maybe because to download it requires a PUT request. My download request looks like this:
https://developer.bigcommerce.com/api/v3/themes.html?python#downloadtheme
```
var BigCommerce = require('node-bigcommerce');

var bigCommerce = new BigCommerce({
  clientId: 'clientId',
  storeHash: 'hash',
  accessToken: 'token',
  responseType: 'json',
  apiVersion: 'v3' // This is new
});

bigCommerce.post('/themes/{themeID}/actions/download', function(err, data, response){
  console.log(data)
});
```

**Comment by dlebech** [comment] 2017-09-06 10:55
@PeteyRev I've re-opened this. I'll see if I can reproduce the issue

**Comment by dlebech** [comment] 2017-09-06 11:23
@PeteyRev I've found out what the trouble is here. The `data` argument is mandatory when using `post` requests, so you need to call the endpoint like this:
```javascript
// The added null is the data
bigCommerce.post('/themes/{themeID}/actions/download', null, function(err, data, response){
  console.log(data)
});
```
By the way, if it's possible for you, I would suggest using the promise-based version of the call like this:
```javascript
bigCommerce.post('/themes/{themeID}/actions/download')
  .then(console.log)
  .catch(console.error);
});
```

However, that will currently give you a 400 error from the BigCommerce API with no explanation of the error. Perhaps it's because of the missing `which` parameter. It's mentioned in the docs, but there's no example of its usage.

This seems to work for me:
```javascript
bigCommerce.post('/themes/a-very-long-uuid/actions/download', { which: 'original' })
  .then(console.log)
  .catch(console.error);
```
I hope this helps.

**Closed by dlebech** 2017-09-06 11:23 UTC

**Comment by PeteyRev** [comment] 2017-09-06 15:59
@dlebech Thanks for all your help on this - Do I need to specify a download folder or anything? When I am running this is the response I get

`$ node app.js
{ job_id: 'faace50abb39d329c75de235238aa2b6' }
`

But nothing is downloading.

**Comment by dlebech** [comment] 2017-09-06 16:12
@PeteyRev From what I can tell in the docs, this action actually starts a background job, but I don't know what this background job does and how to fetch the result from it. This is what [the docs](https://developer.bigcommerce.com/api/v3/themes.html#downloadtheme) say about the response:

> Job ID for the background job processing the download.

I think BigCommerce developer support would be the best people to ask about the specifics of this API. I didn't know about it until today :-)

**Comment by PeteyRev** [comment] 2017-09-06 17:27
@dlebech Haha sorry to keep bugging you, yea I will definitely hit them up and let you know what I find.

**Comment by dlebech** [comment] 2017-09-06 17:55
Hehe, no worries @PeteyRev . I'm happy we were able to solve the main problem of V3 access. Hopefully, the documentation for it improves over time, especially when they are encouraging people to start the switch. We'll probably stick to V2 for now 😄 

Cheers 🍻
